name: kids_ev_controller
description: "remotely operate and monitor an electric car for kids controlled by RaspberryPi from a smartphone"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.1


  cupertino_icons: ^1.0.8
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  build_runner: ^2.4.11
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  flutter_mqtt: ^1.0.0+5
  mqtt_client: ^10.3.0
  speech_to_text: ^7.0.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.2
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env
